/**
 * Supabase database types — manually maintained.
 * Based on migration files + live DB columns added in Sprint 5 prep.
 *
 * Columns marked "Sprint 5" were added directly to the DB without migration files
 * (task_prefix, display_id, parent_task_id, ready_to_advance, sprint_id, sprints table).
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          auth_id: string | null;
          email: string;
          name: string;
          role: "admin" | "operator" | "stakeholder";
          company_role: string | null;
          avatar_url: string | null;
          bio: string | null;
          responsibilities: string | null;
          dedication: "full_time" | "partial" | null;
          partnership_type: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["users"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
      };

      projects: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          phase: "discovery" | "mvp" | "validation" | "traction" | "scale" | "paused" | "closed";
          status: "active" | "paused" | "closed";
          owner_id: string | null;
          thesis_type: "b2c" | "b2b" | null;
          thesis_hypothesis: string | null;
          linear_team_id: string | null;
          launch_target: string | null;
          logo_url: string | null;
          stripe_product_id: string | null;
          task_prefix: string | null; // Sprint 5
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["projects"]["Row"], "id" | "created_at" | "status"> & {
          id?: string;
          status?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["projects"]["Insert"]>;
      };

      project_members: {
        Row: {
          project_id: string;
          user_id: string;
          role_in_project: string;
        };
        Insert: Database["public"]["Tables"]["project_members"]["Row"];
        Update: Partial<Database["public"]["Tables"]["project_members"]["Row"]>;
      };

      tasks: {
        Row: {
          id: string;
          project_id: string | null;
          title: string;
          description: string | null;
          type: "dev" | "task" | "meeting_prep" | "report" | "research" | "decision" | "growth" | "design" | "ops";
          assignee_id: string | null;
          status: "backlog" | "doing" | "on_hold" | "review" | "done" | "cancelled";
          priority: "low" | "medium" | "high" | "urgent";
          due_date: string | null;
          tags: string[];
          linear_issue_id: string | null;
          display_id: string | null; // Sprint 5 — generated by trigger
          parent_task_id: string | null; // Sprint 5
          ready_to_advance: boolean | null; // Sprint 5
          sprint_id: string | null; // Sprint 5
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["tasks"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          display_id?: string; // trigger auto-generates if omitted
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tasks"]["Insert"]>;
      };

      task_blocks: {
        Row: {
          id: string;
          task_id: string;
          reason: string;
          blocked_by_user_id: string | null;
          resolved: boolean;
          resolved_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["task_blocks"]["Row"], "id" | "created_at" | "resolved"> & {
          id?: string;
          resolved?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["task_blocks"]["Insert"]>;
      };

      sprints: {
        Row: {
          id: string;
          project_id: string;
          number: number;
          name: string;
          status: "planning" | "active" | "completed";
          starts_at: string | null;
          ends_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["sprints"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sprints"]["Insert"]>;
      };

      documents: {
        Row: {
          id: string;
          title: string;
          content: string | null;
          type: "contexto" | "prd" | "spec" | "aprendizado" | "ata" | "template" | "relatorio" | "livre";
          project_id: string | null;
          version: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["documents"]["Row"], "id" | "created_at" | "updated_at" | "version"> & {
          id?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["documents"]["Insert"]>;
      };

      document_versions: {
        Row: {
          id: string;
          document_id: string;
          version: number;
          title: string;
          content: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["document_versions"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["document_versions"]["Insert"]>;
      };

      meetings: {
        Row: {
          id: string;
          project_id: string | null;
          title: string;
          description: string | null;
          type: "internal" | "standup" | "review" | "planning" | "retro" | "external" | "one_on_one";
          status: "scheduled" | "in_progress" | "completed" | "cancelled";
          scheduled_at: string;
          duration_minutes: number | null;
          location: string | null;
          meeting_url: string | null;
          notes: string | null;
          recording_url: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["meetings"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["meetings"]["Insert"]>;
      };

      meeting_participants: {
        Row: {
          meeting_id: string;
          user_id: string;
          role: "organizer" | "participant" | "optional";
          rsvp: "pending" | "accepted" | "declined" | "tentative";
        };
        Insert: Omit<Database["public"]["Tables"]["meeting_participants"]["Row"], "role" | "rsvp"> & {
          role?: string;
          rsvp?: string;
        };
        Update: Partial<Database["public"]["Tables"]["meeting_participants"]["Insert"]>;
      };

      decisions: {
        Row: {
          id: string;
          project_id: string | null;
          meeting_id: string | null;
          title: string;
          description: string | null;
          status: "proposed" | "approved" | "rejected" | "deferred" | "superseded";
          impact: "low" | "medium" | "high" | "critical" | null;
          decided_at: string | null;
          decided_by: string | null;
          context: string | null;
          rationale: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["decisions"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["decisions"]["Insert"]>;
      };

      action_items: {
        Row: {
          id: string;
          meeting_id: string | null;
          decision_id: string | null;
          task_id: string | null;
          title: string;
          assignee_id: string | null;
          due_date: string | null;
          status: "pending" | "done" | "cancelled";
          completed_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["action_items"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["action_items"]["Insert"]>;
      };

      reports: {
        Row: {
          id: string;
          project_id: string | null;
          title: string;
          type: "weekly" | "monthly" | "quarterly" | "custom" | "investor";
          period_start: string | null;
          period_end: string | null;
          content: string | null;
          data_json: Json | null;
          status: "draft" | "published";
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["reports"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["reports"]["Insert"]>;
      };

      metrics_snapshots: {
        Row: {
          id: string;
          project_id: string;
          date: string;
          data_json: Json;
          source: "manual" | "stripe" | "api";
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["metrics_snapshots"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["metrics_snapshots"]["Insert"]>;
      };

      company_metrics: {
        Row: {
          id: string;
          date: string;
          total_mrr: number | null;
          total_clients: number | null;
          runway_months: number | null;
          burn_rate: number | null;
          data_json: Json | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["company_metrics"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["company_metrics"]["Insert"]>;
      };

      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          entity_type: string | null;
          entity_id: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["notifications"]["Row"], "id" | "created_at" | "is_read"> & {
          id?: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["notifications"]["Insert"]>;
      };

      activity_log: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["activity_log"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activity_log"]["Insert"]>;
      };

      linear_sync_config: {
        Row: {
          id: string;
          project_id: string;
          team_id: string;
          team_name: string;
          sync_enabled: boolean;
          webhook_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["linear_sync_config"]["Row"], "id" | "created_at" | "sync_enabled"> & {
          id?: string;
          sync_enabled?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["linear_sync_config"]["Insert"]>;
      };

      linear_sync_log: {
        Row: {
          id: string;
          project_id: string | null;
          task_id: string | null;
          linear_issue_id: string | null;
          direction: "inbound" | "outbound";
          event_type: string;
          status: "success" | "error";
          error_message: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["linear_sync_log"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["linear_sync_log"]["Insert"]>;
      };

      linear_cycles: {
        Row: {
          id: string;
          linear_cycle_id: string;
          project_id: string | null;
          linear_team_id: string;
          name: string | null;
          number: number | null;
          starts_at: string | null;
          ends_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["linear_cycles"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["linear_cycles"]["Insert"]>;
      };

      onboarding_progress: {
        Row: {
          id: string;
          user_id: string;
          step_key: string;
          completed_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["onboarding_progress"]["Row"], "id" | "completed_at"> & {
          id?: string;
          completed_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["onboarding_progress"]["Insert"]>;
      };

      user_settings: {
        Row: {
          user_id: string;
          notification_preferences: Json;
          default_task_view: "list" | "kanban";
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["user_settings"]["Row"], "created_at" | "updated_at"> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["user_settings"]["Insert"]>;
      };
    };
  };
}
